version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: root
  parser:
    build:
      ./parser
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./parser:/parser
  web:
    build: code
    restart: always
    links:
      - db
    depends_on:
       - db
    ports:
      - "8443:8443"
    environment:
      - X_BOT_TOKEN=${X_BOT_TOKEN}
    volumes:
      - ./code:/code
